version: '3.8'
services: 
  app:
    container_name: app-container
    restart: always
    build: ./signupbackend
    ports: 
      - "4000:4000"
    depends_on: 
      - mongo

  client:
    container_name: client-container
    restart: always
    build: ./signupfront
    ports: 
      - "3000:3000"
    depends_on: 
      - app
  
  mongo:
    container_name: mongo-backend
    image: mongo
    expose: 
      - "27017"
    ports: 
      - "27017:27017"
    volumes: 
      - backendDB:/data/db

volumes: 
  backendDB: